<?php

namespace ContainerGtKmLD3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPsychiatre2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3eSJxWD.App\Entity\Psychiatre' shared service.
     *
     * @return \App\Entity\Psychiatre
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3eSJxWD": it needs an instance of "App\\Entity\\Psychiatre" but this type has been excluded in "config/services.yaml".');
    }
}
