<?php

namespace ContainerGtKmLD3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PasswordGenerator' shared autowired service.
     *
     * @return \App\Service\PasswordGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PasswordGenerator.php';

        return $container->privates['App\\Service\\PasswordGenerator'] = new \App\Service\PasswordGenerator();
    }
}
