<?php

namespace Container3M3Njc6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_UxIcons_Command_WarmCacheService extends App_KernelProdContainer
{
    /*
     * Gets the private '.ux_icons.command.warm_cache' shared service.
     *
     * @return \Symfony\UX\Icons\Command\WarmCacheCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['.ux_icons.command.warm_cache'] = $instance = new \Symfony\UX\Icons\Command\WarmCacheCommand(($container->privates['.ux_icons.cache_warmer'] ?? $container->load('get_UxIcons_CacheWarmerService')));

        $instance->setName('ux:icons:warm-cache');
        $instance->setDescription('Warm the icon cache');

        return $instance;
    }
}
