<?php

namespace Container3M3Njc6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFirstControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\FirstController' shared autowired service.
     *
     * @return \App\Controller\FirstController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\FirstController'] = $instance = new \App\Controller\FirstController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\FirstController', $container));

        return $instance;
    }
}
