<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3M3Njc6\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3M3Njc6/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container3M3Njc6.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container3M3Njc6\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container3M3Njc6\App_KernelProdContainer([
    'container.build_hash' => '3M3Njc6',
    'container.build_id' => 'ec9624ba',
    'container.build_time' => 1738266154,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container3M3Njc6');
