<?php

namespace Container1WxlDNm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2lIoHhtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2lIoHht' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2lIoHht'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'psychiatreRepository' => ['privates', 'App\\Repository\\PsychiatreRepository', 'getPsychiatreRepositoryService', true],
        ], [
            'psychiatreRepository' => 'App\\Repository\\PsychiatreRepository',
        ]);
    }
}
