<?php

namespace Container1WxlDNm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NHVKLtOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nHVKLtO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nHVKLtO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'patient' => ['privates', '.errored..service_locator.nHVKLtO.App\\Entity\\Patient', NULL, 'Cannot autowire service ".service_locator.nHVKLtO": it needs an instance of "App\\Entity\\Patient" but this type has been excluded in "config/services.yaml".'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'entityManager' => '?',
            'passwordHasher' => '?',
            'patient' => 'App\\Entity\\Patient',
            'slugger' => '?',
        ]);
    }
}
