<?php

namespace Container1WxlDNm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_CRNCACWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.CRNCACW' shared service.
     *
     * @return \App\Entity\Consultation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ConsultationController::delete()": the $consultation argument is type-hinted with the non-existent class or interface: "App\\Entity\\Consultation".');
    }
}
