<?php

namespace Container1WxlDNm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_KIue7f2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.KIue7f2' shared service.
     *
     * @return \App\Repository\ConsultationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ConsultationController::index()": the $consultationRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\ConsultationRepository".');
    }
}
