<?php

namespace Container1WxlDNm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1nhuQQxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1nhuQQx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1nhuQQx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'consultation' => ['privates', '.errored.OQUcHkK', NULL, 'Cannot determine controller argument for "App\\Controller\\ConsultationController::show()": the $consultation argument is type-hinted with the non-existent class or interface: "App\\Entity\\Consultation".'],
        ], [
            'consultation' => '?',
        ]);
    }
}
